## Assignment 6 - Image Classification

In [1]:
import os, glob
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
from keras.models import Sequential
from glob import glob
from sklearn.metrics import accuracy_score

import warnings
warnings.filterwarnings('ignore')

2023-05-01 12:17:09.228429: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


### Part 01: Data Processing

In [2]:
train_datagen = ImageDataGenerator(rescale=1./255, shear_range=0.2, zoom_range=0.2, horizontal_flip=True)
train_set = train_datagen.flow_from_directory('/Users/parthbansal/Downloads/dataset_train', target_size=(64, 64), batch_size=32, class_mode='categorical')

Found 88 images belonging to 4 classes.


In [3]:
train_set.image_shape

(64, 64, 3)

In [4]:
train_set.num_classes

4

### Part 02: Initial Classifier Build

In [5]:
classifier = Sequential()

2023-05-01 12:17:11.623830: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
classifier.add(Conv2D(filters=32, kernel_size=(3,3), input_shape=(64, 64, 3), activation='relu'))

In [7]:
classifier.add(MaxPooling2D(pool_size=(2,2)))

In [8]:
classifier.add(Conv2D(filters=64, kernel_size=(3,3), activation='relu'))

In [9]:
classifier.add(MaxPooling2D(pool_size=(2,2)))

In [10]:
classifier.add(Flatten())

In [11]:
classifier.add(Dense(units=128, activation='relu'))

In [12]:
classifier.add(Dense(units=train_set.num_classes, activation='softmax'))

In [13]:
classifier.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

### Part 03: Model Runs 

In [30]:
accuracy = np.array([])
steps = np.array([])
epoch = np.array([])

In [14]:
steps_per_epoch = 3
epochs = 3

In [15]:
history = classifier.fit(train_set, steps_per_epoch = steps_per_epoch,epochs = epochs, )

Epoch 1/3
3/3 [==============================] - 1s 170ms/step - loss: 1.6264 - accuracy: 0.2727
Epoch 2/3
3/3 [==============================] - 1s 183ms/step - loss: 0.9391 - accuracy: 0.6136
Epoch 3/3
3/3 [==============================] - 1s 182ms/step - loss: 0.6022 - accuracy: 0.9205


In [16]:
classifier.save('my_model.h5')
print("Saved model")

Saved model


In [23]:
import os, glob
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
model = load_model('my_model.h5')

img_dir = "/Users/parthbansal/Downloads/dataset_test"
data_path = os.path.join(img_dir, '*g')
files = glob.glob(data_path)
    
data = []
results = []
for f1 in files:
    img = image.load_img(f1, target_size = (64, 64))
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis = 0)
    data.append(img)
    result = model.predict(img)
    r = np.argmax(result, axis=1)
    results.append(r)

results

1/1 [==============================] - 0s 14ms/step


[array([3]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([2]),
 array([1]),
 array([1])]

In [18]:
train_set.class_indices

{'category 1': 0, 'category 2': 1, 'category 3': 2, 'category 4': 3}

In [25]:
train_set.labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
      dtype=int32)

In [28]:
test_labels = [3,0,2,0,1,2,3,1]
print("Test set accuracy:", accuracy_score(test_labels, results))

Test set accuracy: 0.75


In [33]:
for e in range(1,4):
    results=[]
    classifier = create_classifier(input_shape)
    classifier.fit(train_set, steps_per_epoch = 1,epochs = e)
    for d in range(len(data)):
        result = classifier.predict(data[d])
        r = np.argmax(result, axis=1)
        results.append(r)
    acc = accuracy_score(test_label, results)
    print(acc)
    accuracy= np.append(accuracy,acc)
    steps= np.append(steps,1)
    epoch= np.append(epoch,e) 

1/1 [==============================] - 0s 14ms/step
0.25
Epoch 1/2
1/1 [==============================] - 0s 447ms/step - loss: 1.2976 - accuracy: 0.4062
Epoch 2/2
1/1 [==============================] - 0s 15ms/step
0.5
Epoch 1/3
1/1 [==============================] - 0s 478ms/step - loss: 1.3661 - accuracy: 0.2812
Epoch 2/3
1/1 [==============================] - 0s 239ms/step - loss: 1.6728 - accuracy: 0.2812
Epoch 3/3
1/1 [==============================] - 0s 15ms/step
0.375


In [34]:
for e in range(4,7):
    results=[]
    classifier = create_classifier(input_shape)
    classifier.fit(train_set, steps_per_epoch = 2,epochs = e)
    for d in range(len(data)):
        result = classifier.predict(data[d])
        r = np.argmax(result, axis=1)
        results.append(r)
    acc = accuracy_score(test_label, results)
    print(acc)
    accuracy= np.append(accuracy,acc)
    steps= np.append(steps,2)
    epoch= np.append(epoch,e)  

Epoch 1/4
2/2 [==============================] - 1s 208ms/step - loss: 1.6901 - accuracy: 0.3438
Epoch 2/4
2/2 [==============================] - 0s 145ms/step - loss: 1.5676 - accuracy: 0.3393
Epoch 3/4
2/2 [==============================] - 0s 144ms/step - loss: 0.8331 - accuracy: 0.8214
Epoch 4/4
1/1 [==============================] - 0s 15ms/step
0.625
Epoch 1/5
2/2 [==============================] - 1s 153ms/step - loss: 1.2593 - accuracy: 0.4107
Epoch 2/5
2/2 [==============================] - 0s 152ms/step - loss: 0.9586 - accuracy: 0.6071
Epoch 3/5
2/2 [==============================] - 0s 209ms/step - loss: 0.5121 - accuracy: 0.7969
Epoch 4/5
2/2 [==============================] - 0s 221ms/step - loss: 0.4049 - accuracy: 0.8929
Epoch 5/5
1/1 [==============================] - 0s 15ms/step
0.875
Epoch 1/6
2/2 [==============================] - 1s 215ms/step - loss: 3.0347 - accuracy: 0.2143
Epoch 2/6
2/2 [==============================] - 0s 213ms/step - loss: 1.4439 - accuracy

In [35]:
for e in range(7,9):
    results=[]
    classifier = create_classifier(input_shape)
    classifier.fit(train_set, steps_per_epoch = 3,epochs = e)
    for d in range(len(data)):
        result = classifier.predict(data[d])
        r = np.argmax(result, axis=1)
        results.append(r)
    acc = accuracy_score(test_label, results)
    print(acc)
    accuracy= np.append(accuracy,acc)
    steps= np.append(steps,3)
    epoch= np.append(epoch,e)   

Epoch 1/7
3/3 [==============================] - 1s 208ms/step - loss: 1.7895 - accuracy: 0.3182
Epoch 2/7
3/3 [==============================] - 1s 212ms/step - loss: 1.0310 - accuracy: 0.6250
Epoch 3/7
3/3 [==============================] - 1s 182ms/step - loss: 0.7069 - accuracy: 0.7614
Epoch 4/7
3/3 [==============================] - 1s 182ms/step - loss: 0.4420 - accuracy: 0.9091
Epoch 5/7
3/3 [==============================] - 1s 173ms/step - loss: 0.2931 - accuracy: 0.9432
Epoch 6/7
3/3 [==============================] - 1s 172ms/step - loss: 0.1923 - accuracy: 0.9545
Epoch 7/7
1/1 [==============================] - 0s 13ms/step
0.875
Epoch 1/8
3/3 [==============================] - 1s 205ms/step - loss: 1.5509 - accuracy: 0.2386
Epoch 2/8
3/3 [==============================] - 1s 210ms/step - loss: 0.9740 - accuracy: 0.7045
Epoch 3/8
3/3 [==============================] - 1s 210ms/step - loss: 0.5235 - accuracy: 0.9205
Epoch 4/8
3/3 [==============================] - 1s 189ms/s

In [39]:
for e in range(9,11):
    print('Epoch', e)
    batches = 0
    for x_batch, y_batch in train_datagen.flow_from_directory('/Users/parthbansal/Downloads/dataset_train', target_size=(64, 64), batch_size = 32, class_mode = 'categorical', seed = 74):
        classifier = create_classifier(input_shape)
        classifier.fit(x_batch, y_batch, steps_per_epoch = 5,epochs = e)
        batches += 1
        if batches >= n_batch:
            break
    results=[]
    for d in range(len(data)):
        result = classifier.predict(data[d])
        r = np.argmax(result, axis=1)
        results.append(r)
    acc = accuracy_score(test_label, results)
    print(acc)
    accuracy= np.append(accuracy,acc)
    steps= np.append(steps,5)
    epoch= np.append(epoch,e) 

Epoch 9
Found 88 images belonging to 4 classes.
Epoch 1/9
5/5 [==============================] - 0s 9ms/step - loss: 1.7411 - accuracy: 0.4062
Epoch 2/9
5/5 [==============================] - 0s 11ms/step - loss: 0.7965 - accuracy: 0.7500
Epoch 3/9
5/5 [==============================] - 0s 11ms/step - loss: 0.3889 - accuracy: 0.9375
Epoch 4/9
5/5 [==============================] - 0s 11ms/step - loss: 0.2137 - accuracy: 0.8750
Epoch 5/9
5/5 [==============================] - 0s 11ms/step - loss: 0.0756 - accuracy: 0.9688
Epoch 6/9
5/5 [==============================] - 0s 10ms/step - loss: 0.0206 - accuracy: 1.0000
Epoch 7/9
5/5 [==============================] - 0s 10ms/step - loss: 0.0116 - accuracy: 1.0000
Epoch 8/9
5/5 [==============================] - 0s 9ms/step - loss: 0.0049 - accuracy: 1.0000
Epoch 9/9
5/5 [==============================] - 0s 10ms/step - loss: 0.0014 - accuracy: 1.0000
Epoch 1/9
5/5 [==============================] - 0s 9ms/step - loss: 1.9106 - accuracy: 0.

In [45]:
results

accuracy  epochs  steps per epoch
0     0.250     1.0              1.0
1     0.500     2.0              1.0
2     0.375     3.0              1.0
3     0.625     4.0              2.0
4     0.875     5.0              2.0
5     0.750     6.0              2.0
6     0.875     7.0              3.0
7     0.875     8.0              3.0
8     0.750     9.0              5.0
9     0.750    10.0              5.0

### Part 04: Conceptual Questions 

**4. Discuss the effect of the following on accuracy and loss (train & test):** 
    **Increasing the steps_per_epoch**
    **Increasing the number of epochs**
- Increasing the steps_per_epoch can lead to a more precise update of the weights in the neural network, which can improve both the training and testing accuracy. However, increasing the number of epochs can lead to overfitting, which can reduce the testing accuracy while improving the training accuracy. 

**5. Name two uses of zero padding in CNN.**
- To preserve spatial resolution of the input image during convolutional layers. Without padding, the output feature maps are smaller than the input, and it can lead to the loss of important information on the edges or corners of the image. 
- To allow for the detection of features at the image borders. When using convolutional filters on the edges of an image, some parts of the filter may lie outside of the image and be discarded. By padding the image with zeros, the edges of the image can be extended, allowing the filter to detect features at the borders.

**6. What is the use of a 1 x 1 kernel in CNN?** 
- Reducing the number of channels or feature maps. By applying a 1 x 1 kernel to each input channel, we can reduce the number of channels in the output feature map. Also, it can help for non-linear transformations of feature maps.

**7. What are the advantages of a CNN over a fully connected DNN for this image classification problem?**
- It has less number of parameters compared to a fully connected DNN and allows for more efficient training.
- CNNs are able to recognize the same feature regardless of its location in the input image, making them more robust to translation and distortion.
- It requires much less training data